from datetime import datetime
import time


# ================= UTILITIES =================

def print_header(title):
    print("\n" + "=" * 60)
    print(title)
    print("=" * 60)


def log_event(message):
    with open("auto_logs.txt", "a") as log:
        log.write(f"{datetime.now()} - {message}\n")


def generate_report(content):
    with open("auto_report.txt", "w") as report:
        report.write(content)


# ================= VEHICLE INPUT =================

def get_vehicle_info():
    print_header("Vehicle Information")
    brand = input("Car Brand: ")
    model = input("Car Model: ")
    year = input("Model Year: ")
    engine = input("Engine Type (Petrol / Diesel): ")

    return {
        "brand": brand,
        "model": model,
        "year": year,
        "engine": engine
    }


# ================= OBD DIAGNOSTIC ENGINE =================

def diagnose_obd_code(code):
    obd_database = {
        "P0171": {
            "issue": "System Too Lean",
            "cause": "Vacuum leak or faulty oxygen sensor",
            "solution": "Check vacuum hoses and O2 sensor"
        },
        "P0300": {
            "issue": "Random/Multiple Cylinder Misfire",
            "cause": "Spark plugs or ignition coils",
            "solution": "Inspect spark plugs and ignition coils"
        },
        "P0420": {
            "issue": "Catalyst System Efficiency Below Threshold",
            "cause": "Faulty catalytic converter or O2 sensor",
            "solution": "Check catalytic converter and oxygen sensors"
        }
    }

    return obd_database.get(code.upper(), None)


# ================= SYMPTOM-BASED DIAGNOSIS =================

def diagnose_by_symptom():
    print_header("Select Symptom")
    print("1. Engine shaking")
    print("2. High fuel consumption")
    print("3. Check engine light ON")
    print("4. Hard starting")

    choice = input("Enter choice: ")

    if choice == "1":
        return "Possible misfire detected. Check spark plugs and ignition coils."
    elif choice == "2":
        return "Fuel system issue. Possible O2 sensor or injector problem."
    elif choice == "3":
        return "ECU detected a fault. OBD scan recommended."
    elif choice == "4":
        return "Starting system or fuel pressure issue."
    else:
        return "Unknown symptom."


# ================= MAIN PROGRAM =================

def main():
    print_header("Automotive Diagnostic Simulator")
    log_event("Program started")

    vehicle = get_vehicle_info()

    print_header("Diagnostic Mode")
    print("1. Diagnose by OBD Code")
    print("2. Diagnose by Symptoms")

    mode = input("Select mode: ")

    diagnosis_result = ""

    if mode == "1":
        code = input("Enter OBD Code (e.g. P0171): ")
        result = diagnose_obd_code(code)

        if result:
            diagnosis_result = (
                f"Issue: {result['issue']}\n"
                f"Possible Cause: {result['cause']}\n"
                f"Recommended Solution: {result['solution']}"
            )
        else:
            diagnosis_result = "OBD Code not found in database."

    elif mode == "2":
        diagnosis_result = diagnose_by_symptom()

    else:
        diagnosis_result = "Invalid diagnostic mode selected."

    print_header("Diagnosis Result")
    print(diagnosis_result)

    report = f"""
AUTOMOTIVE DIAGNOSTIC REPORT
Date: {datetime.now()}

Vehicle:
Brand: {vehicle['brand']}
Model: {vehicle['model']}
Year: {vehicle['year']}
Engine: {vehicle['engine']}

Diagnosis Result:
{diagnosis_result}

Generated by Ahmed Anter
"""

    generate_report(report)
    log_event("Diagnosis completed")

    print("\n✔ Diagnostic report generated: auto_report.txt")


if __name__ == "__main__":
    main()
